
import axios from 'axios';

// Bộ tag mẫu (rút gọn các tag quan trọng nhất từ danh sách bạn gửi để đảm bảo hiệu năng)
export const LOCAL_TAGS = [
  "1girl", "solo", "long_hair", "breasts", "looking_at_viewer", "blush", "smile", "open_mouth", 
  "short_hair", "blue_eyes", "simple_background", "shirt", "large_breasts", "skirt", "blonde_hair",
  "multiple_girls", "brown_hair", "black_hair", "long_sleeves", "hair_ornament", "white_background",
  "1boy", "gloves", "red_eyes", "dress", "thighhighs", "hat", "holding", "bow", "navel", "animal_ears",
  "ribbon", "hair_between_eyes", "closed_mouth", "2girls", "cleavage", "jewelry", "bare_shoulders",
  "very_long_hair", "sitting", "twintails", "medium_breasts", "brown_eyes", "standing", "nipples",
  "green_eyes", "underwear", "blue_hair", "jacket", "school_uniform", "purple_eyes", "collarbone",
  "tail", "white_shirt", "full_body", "upper_body", "panties", "closed_eyes", "yellow_eyes",
  "swimsuit", "white_hair", "pink_hair", "monochrome", "grey_hair", "ahoge", "braid", "hair_ribbon",
  "purple_hair", "male_focus", "ponytail", "ass", "flower", "weapon", "multicolored_hair",
  "short_sleeves", "sidelocks", "comic", "hetero", "heart", "thighs", "hair_bow", "pantyhose",
  "outdoors", "cowboy_shot", "earrings", "greyscale", "bikini", "sweat", "red_hair", "nude",
  "pleated_skirt", "small_breasts", "frills", "hairband", "parted_lips", "censored", "boots",
  "open_clothes", "lying", "horns", "teeth", "multiple_boys", "wings", "food", "necktie",
  "one_eye_closed", "detached_sleeves", "sky", "penis", "shorts", "green_hair", "japanese_clothes",
  "shoes", "sleeveless", "black_gloves", "alternate_costume", "collared_shirt", "choker", "barefoot",
  "pussy", "socks", "glasses", "tongue", "pointy_ears", "solo_focus", "pants", "day", "indoors",
  "puffy_sleeves", "hairclip", "medium_hair", "belt", "fang", "black_thighhighs", "hand_up",
  "elbow_gloves", "midriff", "looking_back", "cloud", "white_gloves", "signature", "bowtie",
  "hood", "sword", "black_skirt", "dark_skin", "cat_ears", "blunt_bangs", "hair_flower",
  "tongue_out", "sex", "spread_legs", "pink_eyes", "sailor_collar", "wide_sleeves", "miniskirt",
  "stomach", "fingerless_gloves", "cum", "on_back", "tears", "black_footwear", "grey_background",
  "3girls", "armpits", "kimono", "white_dress", "off_shoulder", "necklace", "striped_clothes",
  "hair_bun", "nail_polish", "from_behind", "mole", "water", "bag", "rabbit_ears", "chibi",
  "orange_hair", "blurry", "grin", "sweatdrop", "clothes_lift", "black_dress", "scarf", "cape",
  "white_thighhighs", "black_eyes", "two-tone_hair", "bra", "yuri", "armor", "huge_breasts",
  "vest", "open_jacket", "halo", "from_side", "apron", "feet", "red_bow", "arm_up", "white_panties",
  "leotard", "coat", "black_jacket", "vaginal", "high_heels", "collar", "arms_up", "sweater",
  "bracelet", "blue_sky", "flat_chest", "twin_braids", "uniform", "side_ponytail", "red_ribbon",
  "crop_top", "aqua_eyes", "black_shirt", "covered_nipples", "parted_bangs", "completely_nude",
  "blue_skirt", "fingernails", "black_pantyhose", "tree", "hands_up", "grey_eyes", "orange_eyes",
  "legs", "neckerchief", "sketch", "groin", "eyelashes", "wet", "fur_trim", "see-through", "lips",
  "wrist_cuffs", "loli", "pillow", "head_tilt", "gun", "maid", "strapless", "zettai_ryouiki",
  "plaid", "torn_clothes", "fox_ears", "toes", "multiple_views", "one-piece_swimsuit", "book",
  "sash", "short_shorts", "bare_arms", "pubic_hair", "shiny_skin", "cosplay", "sparkle",
  "muscular", "petals", "kneehighs", "bare_legs", "window", "uncensored", "thigh_strap",
  "black_bow", "single_braid", "covered_navel", "hoodie", "neck_ribbon", "black_ribbon",
  "gradient_hair", "tattoo", "black_choker", "dress_shirt", "buttons", "double_bun", "profile",
  "sideboob", "kneeling", "makeup", "blood", "bell", "military", "hug", "saliva", "floating_hair",
  "aqua_hair", "mask", "pov", "colored_skin", "anus", "bodysuit", "leaning_forward", "facial_hair",
  "blue_dress", "night", "shadow", "black_pants", "pussy_juice", "bed", "no_bra", "black_bikini",
  "heterochromia", "depth_of_field", "nose_blush", "white_headwear", "red_skirt", "blue_bow",
  "turtleneck", "fruit", "fox_tail", "blue_background", "border", "underboob", "watermark",
  "witch_hat", "cum_in_pussy", "siblings", "highleg", "military_uniform", "expressionless",
  "frown", "bird", "no_panties", "on_bed", "rose", "cameltoe", "headband", "glowing", "black_shorts",
  "scar", "horse_ears", "bottomless", "beret", "ocean", "soles", "animal", "holding_hands",
  "wavy_hair", "fangs", "halterneck", "thick_thighs", "leaf", "chain", "playboy_bunny",
  "headphones", "piercing", "from_above", "embarrassed", "white_jacket", "holding_sword",
  "white_socks", "back", "chinese_clothes", "white_bikini", "erection", "phone", "no_shoes",
  "facial_mark", "chair", "thick_eyebrows", "plaid_skirt", "abs", "umbrella", "looking_down",
  "bandages", "beach", "thigh_boots", "sandals", "on_side", "female_pubic_hair", "muscular_male",
  "bob_cut", "short_dress", "drill_hair", "arms_behind_back", "sunglasses", "happy", "pectorals",
  "red_dress", "testicles", "shirt_lift", "eating", "grabbing", "transparent_background",
  "pink_background", "stuffed_toy", "dark-skinned_male", "hood_down", "frilled_dress", "squatting",
  "clothes_pull", "cleavage_cutout", "white_skirt", "table", "blue_shirt", "crossed_arms",
  "thigh_gap", "from_below", "leg_up", "ring", "oral", "holding_food", "bound", "wolf_ears",
  "blue_jacket", "black_socks", "moon", "black_hairband", "white_flower", "eyepatch", "scrunchie",
  "skirt_lift", "sunlight", "white_bow", "formal", "topless", "cat", "demon_girl", "cat_girl",
  "trembling", "cardigan", "backpack", "magical_girl", "cellphone", "pantyshot", "crossed_legs",
  "grass", "demon_horns", "crying", "sharp_teeth", "tank_top", "sleeping", "cloudy_sky", "blazer",
  "suspenders", "high_ponytail", "helmet", "suit", "feathers", "cum_on_body", "bottle", "bdsm",
  "fox_girl", "plant", "black_background", "blue_ribbon", "portrait", "looking_up", "light_smile",
  "school_swimsuit", "straddling", "cross", "fire", "denim", "crown", "knee_boots", "pink_bow",
  "red_necktie", "outstretched_arms", "fellatio", "tiara", "katana", "couple", "breasts_out",
  "red_flower", "on_stomach", "crossover", "robot", "curtains", "spiked_hair", "sisters",
  "girl_on_top", "polka_dot", "black_nails", "knife", "bat_wings", "ear_piercing", "slit_pupils",
  "bent_over", "pointing", "lingerie", "animal_print", "clenched_teeth", "red_shirt", "elf",
  "undressing", "striped_thighhighs", "monster_girl", "sneakers", "black_leotard", "t-shirt",
  "holding_gun", "head_wings", "all_fours", "gem", "red_footwear", "white_apron", "tan", "bondage",
  "furry", "short_twintails", "messy_hair", "lipstick", "green_skirt", "goggles", "brooch",
  "building", "group_sex", "polearm", "black_bra", "horse_tail", "fishnets", "staff", "shaded_face",
  "loafers", "towel", "straight_hair", "cherry_blossoms", "kiss", "feathered_wings", "bandaid",
  "pink_dress", "strapless_leotard", "box", "wind", "facing_viewer", "grey_shirt", "black_necktie",
  "multiple_tails", "drooling", "no_pants", "eyewear_on_head", "demon_tail", "steam", "bike_shorts",
  "yellow_background", "dog_ears", "hooded_jacket", "armband", "casual", "butterfly", "surprised",
  "night_sky", "panty_pull", "sex_toy", "pale_skin", "child", "breast_press", "revealing_clothes",
  "anal", "red_headwear", "gauntlets", "white_ribbon", "rope", "sheath", "china_dress", "pink_panties",
  "knees_up", "candy", "wristband", "between_breasts", "red_background", "couch", "hakama", "blouse",
  "wet_clothes", "musical_note", "hair_over_shoulder", "ejaculation", "scenery", "skin_fang",
  "arms_behind_head", "veil", "nature", "breath", "male_pubic_hair", "red_jacket", "genderswap",
  "red_nails", "lace_trim", "side_braid", "third_eye", "waist_apron", "smartphone", "microphone",
  "facial", "christmas", "large_pectorals", "pink_flower", "pelvic_curtain", "light_blush",
  "strapless_dress", "anger_vein", "baseball_cap", "beard", "string_bikini", "striped_panties",
  "light_particles", "blue_headwear", "claws", "cloak", "toenails", "peaked_cap", "highleg_leotard",
  "glowing_eyes", "white_pupils", "purple_dress", "side-tie_panties", "low_ponytail", "white_pantyhose",
  "jingle_bell", "motor_vehicle", "hand_fan", "grey_skirt", "front-tie_top", "bow_panties", "mecha",
  "buckle", "twin_drills", "areola_slip", "carrying", "clothing_aside", "androgynous", "pink_nails",
  "micro_bikini", "angry", "close-up", "yellow_bow", "maid_apron", "forehead", "hood_up", "wolf_tail",
  "cum_on_breasts", "corset", "neck_bell", "blue_nails", "skin_tight", "paizuri", "rifle", "o-ring",
  "eyeshadow", "tentacles", "black_belt", "lace", "holding_phone", "french_braid", "no_headwear",
  "white_sleeves", "cropped_jacket", "eye_contact", "curvy", "faceless", "licking", "bikini_top_only",
  "brown_gloves", "plate", "restrained", "snow", "red_gloves", "mary_janes", "full_moon", "spikes",
  "tearing_up", "black_wings", "science_fiction", "blue_bikini", "holding_book", "side_slit", "gift",
  "desk", "black_coat", "camisole", "finger_to_mouth", "ball", "strap_slip", "armlet", "green_bow",
  "single_horn", "lens_flare", "cowgirl_position", "floating", "dragon_horns", "drinking_glass",
  "arm_at_side", "sleeves_rolled_up", "seiza", "gold_trim", "puffy_nipples", "blue_necktie",
  "santa_hat", "after_sex", "wide_hips", "pink_skirt", "single_glove", "pink_ribbon", "veins",
  "smoke", "handgun", "heavy_breathing", "between_legs", "zipper", "knee_up", "brown_background",
  "starry_sky", "masturbation", "blue_flower", "handjob", "open_coat", "freckles", "blue_shorts",
  "demon_wings", "wading", "pencil_skirt", "happy_birthday", "fish", "green_background", "pink_shirt",
  "alcohol", "clothed_sex", "pendant", "ribbed_sweater", "topless_male", "high_heel_boots",
  "track_jacket", "single_earring", "outline", "frilled_apron", "spot_color", "tray", "swim_ring",
  "sweater_vest", "purple_background", "reflection", "forest", "upskirt", "legs_up", "headset",
  "black_vest", "frilled_bikini", "walking", "cake", "white_skin", "beads", "pocket", "personification",
  "backlighting", "halloween", "bulge", "dress_lift", "green_dress", "unworn_headwear", "legs_apart",
  "long_fingernails", "toned", "broom", "arm_behind_head", "brown_pantyhose", "thong", "condom",
  "red_bikini", "short_ponytail", "out_of_frame", "purple_bow", "long_skirt", "rain", "blue_footwear",
  "crossdressing", "angel_wings", "white_bra", "cuffs", "flying", "gym_uniform", "cumdrip",
  "purple_skirt", "yellow_shirt", "one_eye_covered", "bubble", "black_bowtie", "braided_ponytail",
  "fingering", "epaulettes", "curly_hair", "empty_eyes", "santa_costume", "futanari", "teacup",
  "high_collar", "brown_jacket", "tanlines", "rape", "denim_shorts", "brown_skirt", "bowl",
  "dragon_girl", "animal_hands", "innertube", "side_burns", "buruma", "contrapposto", "white_pants",
  "school_bag", "jitome", "pouch", "doggystyle", "faceless_male", "cigarette", "dual_wielding",
  "breast_hold", "red_scarf", "fur_collar", "green_jacket", "sailor_dress", "asymmetrical_hair",
  "robe", "spread_pussy", "garter_belt", "white_shorts", "machinery", "pauldrons", "dog_tail",
  "cum_in_mouth", "legs_together", "yellow_ribbon", "lolita_fashion", "head_rest", "running",
  "top_hat", "sun_hat", "plump", "furry_female", "white_hairband", "ass_grab", "threesome", "watch",
  "fake_tail", "blood_on_face", "sunset", "blue_one-piece_swimsuit", "twins", "turtleneck_sweater",
  "monster", "dog", "white_kimono", "sports_bra", "drinking_straw", "white_wings", "grey_jacket",
  "aged_up", "new_year", "poke_ball", "wide-eyed", "skull", "shield", "shiny_clothes", "mature_female",
  "female_masturbation", "white_coat", "missionary", "striped_shirt", "jeans", "yellow_flower",
  "rabbit", "ghost", "circlet", "red_rose", "belt_buckle", "teddy_bear", "hair_down", "blue_theme",
  "ice", "paper", "shoulder_bag", "green_shirt", "serious", "stubble", "spear", "sarashi", "paw_pose",
  "striped_bikini", "crystal", "wooden_floor", "shawl", "injury", "hairpin", "rabbit_girl", "rock",
  "lantern", "sheathed", "purple_flower", "mug", "bouncing_breasts", "unworn_hat", "popsicle",
  "blue_bowtie", "lollipop", "long_legs", "smirk", "green_headwear", "wolf_girl", "mirror", "yukata",
  "upside-down", "water_drop", "light_blue_hair", "bouquet", "mini_hat", "white_leotard",
  "purple_shirt", "military_hat", "reaching", "breastplate", "pajamas", "brown_headwear", "snowing",
  "black_sleeves", "blue_pants", "bespectacled", "light_rays", "butt_crack", "dragon_tail", "oni",
  "striped_bow", "open_book", "glint", "mouth_mask", "handbag", "ass_focus", "blue_panties",
  "pink_lips", "stairs", "animal_hood", "collared_dress", "waving", "short_eyebrows", "chocolate",
  "fins", "orange_background", "city", "jumping", "chopsticks", "tabard", "mustache", "double_v",
  "sign", "long_dress", "on_floor", "sportswear", "leash", "card", "pout", "veiny_penis", "mountain",
  "turret", "dog_girl", "outstretched_hand", "can", "sand", "large_penis", "contemporary", "blue_skin",
  "ice_cream", "spoon", "valentine", "pink_footwear", "vibrator", "strawberry", "goatee", "lab_coat",
  "panties_aside", "underwater", "cum_overflow", "black_one-piece_swimsuit", "drink", "fence",
  "muscular_female", "nipple_stimulation", "fighting_stance", "red_hairband", "nose", "hime_cut",
  "mouse_ears", "hair_bell", "skirt_hold", "music", "wedding_dress", "blue_kimono", "railing", "fork",
  "nurse_cap", "purple_ribbon", "bloomers", "dragon", "red_cape", "hat_flower", "hair_tie",
  "palm_tree", "blue_gloves", "purple_nails", "miko", "realistic", "tiles", "door", "pasties",
  "straw_hat", "green_ribbon", "bandana", "black_bodysuit", "branch", "blue_leotard", "visor_cap",
  "dildo", "orange_bow", "doll", "smoking", "drawstring", "red_vest", "blindfold", "snake",
  "brown_belt", "kneepits", "camera", "licking_lips", "pink_jacket", "logo", "horizon", "black_cape",
  "pink_bra", "interracial", "shota", "anklet", "antennae", "sunflower", "clitoris", "aircraft",
  "white_sweater", "headpiece", "long_bangs", "gag", "eyeliner", "apple", "beanie", "red_lips",
  "bandeau", "white_scarf", "sun", "pink_bikini", "blanket", "folding_fan", "underbust", "groping",
  "gift_box", "spread_arms", "wand", "straight-on", "back_bow", "facing_away", "white_one-piece_swimsuit",
  "tail_ornament", "emblem", "arched_back", "white_outline", "hanging_breasts", "double-breasted",
  "ahegao", "gakuran", "geta", "sailor_hat", "android", "clock", "nun", "angel", "bookshelf", "tabi",
  "leaning_back", "smug", "selfie", "cabbie_hat", "lactation", "basket", "bun_cover", "microskirt",
  "gagged", "car", "guitar", "arm_warmers", "gangbang", "pen", "petticoat", "arm_tattoo",
  "sailor_shirt", "bodystocking", "highleg_swimsuit", "frilled_shirt", "potted_plant", "onsen",
  "habit", "drinking", "body_fur", "yellow_jacket", "unbuttoned", "winter_clothes", "leg_lift",
  "wristwatch", "pool", "lowleg", "summer_uniform", "heart_hands", "gothic_lolita", "cannon",
  "nipple_slip", "electricity", "cow_print", "eyeball", "cow_ears", "brown_shirt", "classroom",
  "antlers", "cheerleader", "glass", "checkered_clothes", "grey_pants", "brown_dress", "silhouette",
  "arm_grab", "taut_clothes", "witch", "vambraces", "overalls", "bush", "pink_headwear", "pocky",
  "black_sweater", "mittens", "black_horns", "blue_thighhighs", "scales", "reading", "layered_sleeves",
  "print_bikini", "headdress", "breast_pocket", "talking", "wince", "candle", "magic", "assault_rifle",
  "petite", "print_kimono", "gohei", "headpat", "controller", "confetti", "wedding_ring", "bangle",
  "cable", "purple_bikini", "huge_ass", "flag", "unzipped", "sundress", "purple_jacket", "road", "lamp",
  "fantasy", "claw_pose", "midriff_peek", "red_kimono", "black_kimono", "animal_focus", "ninja",
  "purple_gloves", "fairy", "cityscape", "joints", "grey_dress", "tube_top", "bare_back", "creature",
  "halloween_costume", "tatami", "open_fly", "scythe", "salute", "beachball", "light", "bench",
  "mini_crown", "nurse", "wet_shirt", "animal_costume", "orgasm", "shoulder_cutout", "blue_rose",
  "bucket", "very_short_hair", "naked_shirt", "half_gloves", "stuffed_rabbit", "riding", "key",
  "white_fur", "space", "femdom", "blue_hairband", "green_skin", "brown_pants", "red_choker",
  "japanese_armor", "black_hoodie", "blue_halo", "anchor", "tiger_ears", "blue_vest", "frog", "haori",
  "office_lady", "undercut", "holster", "waitress", "on_chair", "thighlet", "laughing", "wet_hair",
  "earmuffs", "red_thighhighs", "airplane", "purple_thighhighs", "open_cardigan", "yellow_bikini",
  "naval_uniform", "stretching", "bridal_veil", "incest", "purple_headwear", "shade", "flat_cap",
  "pilot_suit", "precum", "balloon", "dark", "wine_glass", "paw_gloves", "bukkake", "tight_clothes",
  "randoseru", "red_panties", "rigging", "dagger", "battle", "star_print", "paw_print", "pink_kimono",
  "one_breast_out", "id_card", "against_wall", "curled_horns", "purple_panties", "sexually_suggestive",
  "shibari", "belly", "drunk", "bald", "autumn_leaves", "red_hakama", "nipple_piercing", "yellow_dress",
  "bathing", "black_border", "sarong", "red_shorts", "slippers", "bracer", "red_horns", "open_hand",
  "cropped_shirt", "presenting", "snowflakes", "carrot", "animal_hat", "sack", "computer", "arm_strap",
  "raccoon_ears", "evil_smile", "bishounen", "axe", "white_cape", "pink_halo", "teapot", "white_choker",
  "dancing", "vampire", "facepaint", "wide_shot", "scared", "knee_pads", "backless_dress", "on_ground",
  "green_nails", "string", "torn_thighhighs", "print_shirt", "hair_up", "bat_(animal)", "tied_shirt",
  "layered_dress", "torii", "bread", "pumpkin", "squiggle", "bound_arms", "bikini_skirt",
  "architecture", "hibiscus", "red_leotard", "leggings", "green_bikini", "idol", "scabbard",
  "brown_coat", "bedroom", "wagashi", "mouse_tail", "tasuki", "peach", "ribbon_choker", "field",
  "leg_ribbon", "plugsuit", "hat_feather", "short_kimono", "magatama", "white_eyes", "parasol",
  "interspecies", "leather", "transparent", "paintbrush", "head_wreath", "shimenawa", "deep_skin",
  "black_cat", "giant", "yellow_skirt", "aura", "grey_skin", "thumbs_up", "purple_footwear",
  "blue_bra", "harness", "tiger_print", "blue_scarf", "grey_footwear", "tea", "naked_towel",
  "over_shoulder", "two_tails", "stitches", "white_collar", "facial_tattoo", "purple_kimono",
  "white_tank_top", "halftone", "rolling_eyes", "tiptoes", "kicking", "vines", "annoyed", "white_rose",
  "cowbell", "split_mouth", "no_pupils", "black_scarf", "open_kimono", "black_neckerchief", "peeing",
  "strap", "aqua_nails", "old", "pubic_tattoo", "mermaid", "fish_tail", "white_hoodie", "striped_dress",
  "orange_shirt", "blue_cape", "pee", "white_belt", "gyaru", "anniversary", "head_fins", "handcuffs",
  "red_pants", "navel_piercing", "face-to-face", "x-ray", "bathroom", "biting", "magic_circle",
  "spiked_collar", "house", "shackles", "neck_ring", "singing", "pencil", "red_skin", "sad",
  "one-eyed", "explosion", "mushroom", "bamboo", "chest_hair", "falling", "pink_bowtie", "brown_sweater",
  "ruins", "fox_mask", "summer", "belt_pouch", "crescent_moon", "spiked_bracelet", "doughnut",
  "red_coat", "shoe_soles", "water_bottle", "winter", "black_tank_top", "folded", "grey_shorts",
  "lineart", "head_scarf", "greaves", "fireworks", "narrow_waist", "television", "kitsune",
  "leaf_on_head", "goat_horns", "pink_rose", "sunbeam", "monitor", "micro_shorts", "fat", "raccoon_tail",
  "split", "cunnilingus", "camouflage", "arm_cannon", "pink_theme", "striped_necktie", "manly",
  "nervous", "red_capelet", "green_vest", "white_bowtie", "christmas_tree", "brick_wall", "no_shirt",
  "loose_socks", "badge", "other_focus", "dark_persona", "heart_earrings", "stool", "babydoll", "coin",
  "arm_guards", "ooarai_school_uniform", "dark_background", "dark_blue_hair", "brown_shorts", "cookie",
  "undershirt", "brothers", "grey_sweater", "red_theme", "orange_skirt", "hooded_cloak", "bonnet",
  "green_shorts", "dripping", "blue_choker", "blank_eyes", "skirt_pull", "brown_cardigan", "gym_shirt",
  "earphones", "bra_lift", "blue_coat", "bead_bracelet", "fundoshi", "lion_ears", "iron_cross",
  "cutoffs", "white_ascot", "splashing", "tiger_tail", "foreskin", "cow_girl", "hachimaki",
  "white_bodysuit", "pink_gloves", "chalkboard", "playing_card", "shoulder_pads", "drink_can",
  "bikini_armor", "black_sports_bra", "tank", "yellow_bowtie", "pink_thighhighs", "ribs", "ripples",
  "latex", "hammer", "torn_shirt", "animal_collar", "shell", "grey_headwear", "sweater_dress",
  "sakazuki", "futon", "yin_yang", "purple_theme", "syringe", "grey_gloves", "blue_sweater",
  "sandwiched", "birthday", "huge_penis", "sheet_grab", "green_footwear", "planet", "animalization",
  "arm_garter", "zzz", "aqua_necktie", "rice", "arm_ribbon", "watermelon", "rainbow", "old_man",
  "aqua_background", "bridge", "bathtub", "police", "lamppost", "red_collar", "beer", "bear_ears",
  "film_grain", "dirty", "cherry", "shark_tail", "red_halo", "tying_hair", "yellow_footwear", "scroll",
  "cushion", "sheep_horns", "green_kimono", "red_sweater", "insect_wings", "burger", "male_swimwear",
  "scissors", "saucer", "chest_tattoo", "egg", "moaning", "green_panties", "horse", "heads_together",
  "grey_thighhighs", "aiming", "sanpaku", "feeding", "biceps", "shouting", "sleepy", "zouri",
  "collared_jacket", "coffee", "race_queen", "motorcycle", "cooking", "yellow_halo", "fucked_silly",
  "tail_wagging", "navel_hair", "nekomata", "giantess", "no_eyes", "cyborg", "long_coat", "ball_gag",
  "v-neck", "chest_jewel", "extra_arms", "topknot", "blue_hoodie", "tape", "bruise", "gigantic_breasts",
  "shelf", "stomach_bulge", "extra_eyes", "cum_string", "clipboard", "reclining", "sleeveless_jacket",
  "electric_guitar", "green_pants", "green_theme", "bestiality", "jiangshi", "superhero", "single_sock",
  "brown_vest", "skeleton", "yawning", "waist_cape", "shirt_pull", "green_gloves", "hooded_coat",
  "jester_cap", "open_vest", "planted", "plaid_shirt", "cardboard_box", "sake", "monocle",
  "picture_frame", "pink_sweater", "track_suit", "pink_choker", "pillow_hug", "frilled_collar",
  "black_suit", "poolside", "nightgown", "expressions", "punching", "flat_color", "side-by-side",
  "frilled_choker", "striped_bowtie", "beach_umbrella", "pillar", "broken", "white_necktie",
  "jumpsuit", "faulds", "perspective", "police_uniform", "uwabaki", "bride", " yellow_nails",
  "kariginu", "pregnant", "sepia", "wine", "pointy_hair", "chess_piece", "aqua_bow", "front_ponytail",
  "pink_hairband", "sweater_lift", "crack", "baseball_bat", "orb", "pun", "street", "mouse", "footjob",
  "red_bodysuit", "heart_print", "heart_cutout", "lap_pillow", "pervert", "uterus", "shy", "bokeh",
  "plaid_scarf", "side_braids", "flower_field", "laptop", "glaring", "open_hoodie", "tail_bow",
  "red_bra", "purple_bra", "chest_harness", "short_necktie", "blood_splatter", "cross_earrings",
  "halter_dress", "horn_ribbon", "knees", "prosthesis", "cow_tail", "floppy_ears", "river", "dog_tags",
  "gold", "exhibitionism", "shopping_bag", "body_blush", "plaid_bow", "dougi", "purple_lips", "kotatsu",
  "loincloth", "robot_joints", "bra_pull", "purple_necktie", "paper_lantern", "military_jacket", "meat",
  "castle", "dango", "lanyard", "whistle", "leg_tattoo", "faceless_female", "two-tone_fur", "twilight",
  "bound_legs", "white_camisole", "single_wing", "vase", "tomboy", "penguin", "utility_pole",
  "belt_collar", "brown_bow", "red_wings", "thigh_holster", "dressing", "skyscraper", "shorts_pull",
  "suitcase", "bubble_skirt", "striped_socks", "monster_boy", "feet_up", "noodles", "blue_butterfly",
  "waistcoat", "cowboy_hat", "whip", "evening", "damaged", "paper_fan", "autumn", "blue_bodysuit",
  "firing", "knight", "family", "torn_pants", "brown_fur", "bird_tail", "anal_beads", "zombie",
  "albino", "thong_bikini", "flag_print", "water_gun", "white_bloomers", "full_armor", "panty_peek",
  "popped_collar", "chest_sarashi", "onigiri", "wet_panties", "fox", "wolf", "swivel_chair", "waves",
  "yellow_gloves", "pearl_necklace", "large_bow", "armpit_peek", "old_school_swimsuit", "no_socks",
  "tail_ribbon", "snout", "fat_man", "shushing", "rose_petals", "blue_sleeves", "yandere", "bird_ears",
  "maebari", "orange_jacket", "purple_leotard", "pink_skin", "cat_boy", "notebook", "beer_mug",
  "shark_girl", "aiguillette", "dolphin_shorts", "amputee", "energy", "mouse_girl", "fur_hat",
  "bicycle", "obijime", "orange_dress", "blue_buruma", "pink_necktie", "crotchless", "suit_jacket",
  "bone", "striped_scarf", "whiskers", "chick", "cane", "grey_vest", "money", "blue_socks", "black_skin",
  "medium_skirt", "frilled_hat", "ship", "open_hands", "striped_skirt", "danmaku", "orange_slice",
  "showgirl_skirt", "striped_ribbon", "recording", "demon", "waist_bow", "quiver", "alien", "blue_fire",
  "red_buruma", "lightning", "hydrangea", "fedora", "cable_knit", "revolver", "unsheathing", "backboob",
  "coffee_mug", "spring_onion", "grey_cardigan", "ladle", "elbow_pads", "crotch", "skinny", "winter_coat",
  "yellow_sweater", "crazy_eyes", "orange_flower", "wine_bottle", "back_cutout", "humanization",
  "statue", "netorare", "locker", "yellow_shorts", "reverse_trap", "cake_slice", "kitchen", "blue_wings",
  "starfish", "orange_bikini", "black_flower", "torn_dress", "throne", "lance", "black_ascot",
  "print_skirt", "ringlets", "butterfly_wings", "hot", "crow", "reverse_grip", "demon_boy", "red_gemstone",
  "crowd", "track_pants", "holding_shield", "knees_to_chest", "crab", "arm_hair", "gears", "pole",
  "muted_color", "pink_neckerchief", "red_scrunchie", "snowman", "stick", "grey_hoodie", "dragon_wings",
  "yellow_fur", "business_suit", "tower", "wedgie", "baggy_pants", "metal_collar", "armchair", "defeat",
  "gourd", "boat", "armpit_hair", "white_vest", "trading_card", "hose", "machine_gun", "evil_grin",
  "road_sign", "lock", "drop_shadow", "yellow_theme", "poking", "blue_capelet", "barcode", "waterfall",
  "pocket_watch", "dark_elf", "purple_hairband", "school", "baby", "clone", "body_markings", "letter",
  "landscape", "trident", "album_cover", "soap_bubbles", "wrist_ribbon", "surgical_mask", "toilet",
  "bustier", "brown_bag", "red_pupils", "pirate_hat", "pouring", "anal_tail", "leather_jacket",
  "trench_coat", "orange_bowtie", "pink_cardigan", "gradient_sky", "bullet", "brown_scarf", "death",
  "lowleg_bikini", "clover", "fusion", "spread_ass", "gym_shorts", "jar", "leg_hair", "no_nipples",
  "bear", "silk", "hairy", "sailor", "puddle", "heart_necklace", "flaccid", "yellow_panties", "milk",
  "blue_ascot", "open_door", "unsheathed", "purple_rose", "backwards_hat", "shop", "library",
  "black_tail", "no_pussy", "red_headband", "strapless_bikini", "nervous_smile", "red_sleeves", "earclip",
  "earpiece", "checkered_skirt", "white_robe", "thorns", "grey_coat", "mobile_suit", "tissue_box",
  "office_chair", "pentagram", "torn_skirt", "macaron", "black_fur", "red_belt", "heart_choker",
  "orange_ribbon", "colorful", "teacher", "black_bag", "tsundere", "flashing", "lake", "policewoman",
  "circle", "defloration", "blue_belt", "spider_web", "small_horns", "viewfinder", "hair_beads", "stage",
  "tiger", "test_tube", "arm_rest", "game_console", "spider_lily", "pink_shorts", "scope", "fog",
  "white_feathers", "fishing_rod", "leaning", "fisheye", "lower_body", "octopus", "lion_tail",
  "remote_control", "envelope", "rapier", "shide", "tight_pants", "dog_boy", "swimming", "charizard",
  "junketsu", "skull_mask", "coral", "grey_kimono", "cafe", "dove", "footprints", "fried_egg", "gown",
  "wooden_bucket", "sparks", "red_armor", "lace_bra", "video_camera", "taiyaki", "trumpet", "turtle",
  "toast", "crepe", "sweet_potato", "keychain", "milk_carton", "baseball", "tanuki", "comb", "spinning",
  "wind_chime", "alarm_clock", "variations", "alley", "barrel", "helm", "blue_sash", "pink_pupils",
  "tripping", "orange_scarf", "holly", "refrigerator", "loose_clothes", "rubble", "hooves", "veranda",
  "seigaiha", "chaps", "whisk", "traffic_light", "faucet", "emoji", "octarian", "wrestling", "ovum",
  "watering_can", "blue_eyeshadow", "star_necklace", "beckoning", "hikimayu", "inverted_bob",
  "birthmark", "squirrel", "chest_strap", "69", "tight_shirt", "brown_necktie", "whipped_cream",
  "failure", "scepter", "crazy_smile", "gold_hairband", "spider_girl", "white_bag", "eyebrow_cut",
  "collared_coat", "swing", "grey_scarf", "cuddling", "birdcage", "pond", "two-handed", "symmetry",
  "teasing", "chasing", "cabinet", "gate", "poncho", "chandelier", "bomb", "warship", "cousins",
  "lip_piercing", "board_game", "thrusters", "ushanka", "bone", "whiskers", "chick", "cane", "money",
  "ship", "quiver", "alien", "lightning", "revolver", "tying", "blob", "medieval", "carapace", "cyrillic",
  "prison", "casino", "storm", "battleship", "scouter", "intestines", "ashtray", "handprint", "math",
  "animal_head", "nebula", "gold_coin", "magician", "elevator", "broccoli", "year_of_the_pig", "cabbage",
  "tire", "sauna", "sparrow", "hole", "wheat", "acorn", "hammock", "thermos", "swinging", "galaxy",
  "ad", "boxcutter", "masochism", "bokken", "credits", "infinity_symbol", "underbutt", "underpec",
  "dragging", "dissolving", "storefront", "handstand", "parka", "head_only", "zora", "how_to", "koi",
  "aurora", "white_lily", "kinchaku", "grave", "crocs", "crumbs", "rope_belt", "polar_bear", "airship",
  "valkyrie", "symbolism", "onion", "drum", "afloat", "contrail", "seagull", "transformation", "sandwich",
  "pumps", "vegetable", "map", "cream", "parfait", "cuts", "banner", "stylus", "briefcase", "baozi",
  "slave", "thinking", "ceiling", "collage", "miniboy", "domino_mask", "egyptian", "updo", "pancake",
  "figure", "what", "toy", "throwing", "arch", "chemise", "attack", "graffiti", "skinny", "statue",
  "locker", "hot", "stick", "tower", "lock", "baby", "clone", "letter", "trident", "toilet", "bullet",
  "death", "jar", "bear", "silk", "milk", "shop", "thorns", "teacher", "circle", "stage", "tiger",
  "leaning", "octopus", "swimming", "cafe", "dove", "gown", "turtle", "toast", "crepe", "baseball",
  "tanuki", "comb", "spinning", "barrel", "helm", "holly", "rubble", "hooves", "faucet", "emoji",
  "wrestling", "ovum", "birthmark", "squirrel", "69", "failure", "scepter", "swing", "pond", "symmetry",
  "teasing", "chasing", "cabinet", "gate", "poncho", "bomb", "cousins", "bone", "whiskers", "chick",
  "cane", "money", "ship", "alien", "blob", "medieval", "carapace", "storm", "math", "nebula",
  "magician", "elevator", "broccoli", "cabbage", "tire", "sauna", "sparrow", "hole", "wheat", "acorn",
  "hammock", "thermos", "swinging", "galaxy", "ad", "bokken", "credits", "dragging", "dissolving",
  "storefront", "handstand", "parka", "zora", "how_to", "koi", "aurora", "grave", "crocs", "crumbs",
  "airship", "valkyrie", "symbolism", "onion", "drum", "afloat", "seagull", "sandwich", "pumps",
  "vegetable", "map", "cream", "parfait", "cuts", "banner", "stylus", "briefcase", "baozi", "slave",
  "thinking", "ceiling", "collage", "miniboy", "egyptian", "updo", "pancake", "figure", "what", "toy"
];

/**
 * Tra cứu tag từ danh sách local và API Danbooru
 */
export const searchTags = async (query: string): Promise<string[]> => {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  // 1. Tìm trong local trước
  const localMatches = LOCAL_TAGS.filter(tag => 
    tag.toLowerCase().startsWith(q)
  ).slice(0, 15);

  // 2. Nếu ít kết quả, gọi Danbooru API
  if (localMatches.length < 10) {
    try {
      const response = await axios.get(`https://danbooru.donmai.us/tags.json`, {
        params: {
          'search[name_matches]': `${q}*`,
          'search[order]': 'count',
          'limit': 15
        }
      });
      
      const apiTags = response.data.map((t: any) => t.name.replace(/_/g, ' '));
      // Hợp nhất và loại trùng
      const combined = Array.from(new Set([...localMatches.map(t => t.replace(/_/g, ' ')), ...apiTags])).slice(0, 15);
      return combined;
    } catch (error) {
      console.error('Danbooru API Error:', error);
      return localMatches.map(t => t.replace(/_/g, ' '));
    }
  }

  return localMatches.map(t => t.replace(/_/g, ' '));
};
